import {api,setupChallenge,statusNames,modelNames,serviceNames} from './portal.js';
const login=document.querySelector('#admin-login');const panel=document.querySelector('#admin-panel');const alert=document.querySelector('#admin-message');const list=document.querySelector('#leads');const detail=document.querySelector('#lead-detail');let challenge;let page=0;let active=null;let items=[];let total=0;let loading=false;
const say=s=>{alert.textContent=s;};
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
async function locked(){panel.hidden=true;login.hidden=false;detail.replaceChildren();active=null;items=[];list.replaceChildren();try{if(!challenge)challenge=await setupChallenge('#admin-challenge','login');login.querySelector('button').disabled=!challenge;if(!challenge)say('Painel ainda não ativado. Siga o arquivo ATIVAR-PAINEL.md do projeto.');}catch(e){say(e.message);}}
async function load(){
 if(loading)return;loading=true;say('Carregando pedidos…');
 try{const r=await api('leads',{query:{page,status:document.querySelector('#filter').value,q:document.querySelector('#search').value}});items=r.items;total=r.total;render();say(total===0?'Nenhum pedido encontrado.':'Pedidos atualizados.');}
 catch(e){say(e.message);if(e.status===401||e.status===403)await locked();}
 finally{loading=false;}
}
function render(){
 list.replaceChildren();document.querySelector('#total').textContent=total;document.querySelector('#page').textContent='Página '+(page+1);document.querySelector('#previous').disabled=page===0;document.querySelector('#next').disabled=(page+1)*30>=total;
 if(!items.length)list.append(node('p','Quando alguém enviar um pedido, ele aparecerá aqui.','empty-state'));
 for(const item of items){const b=node('button','', 'lead-card'+(active?.id===item.id?' selected':''));b.type='button';b.append(node('span',statusNames[item.status],'status-badge'),node('strong',item.business),node('span',item.name+' · '+(modelNames[item.model]||item.model)),node('small',new Date(item.created_at).toLocaleString('pt-BR')));b.addEventListener('click',()=>open(item));list.append(b);}
}
function open(item){
 if(active&&detail.querySelector('form')?.dataset.dirty==='true'&&!confirm('Descartar as alterações ainda não salvas deste pedido?'))return;
 active=item;render();detail.replaceChildren();
 detail.append(node('p','PEDIDO '+item.id.slice(0,8).toUpperCase(),'eyebrow'),node('h2',item.business),node('p',item.name+' · '+item.segment,'muted'));
 const info=document.createElement('dl');for(const [k,v]of [['Serviço',serviceNames[item.service]||serviceNames.site],['Site atual',item.website_url||'Não informado'],['Objetivo',item.goal||'Não informado'],['Prazo',item.timeline||'Não informado'],['Modelo',modelNames[item.model]],['Valor de referência',item.quote_price?'R$ '+item.quote_price.toLocaleString('pt-BR'):'Sob proposta'],['WhatsApp',item.phone],['E-mail',item.email||'Não informado'],['Necessidade',item.need]]){info.append(node('dt',k),node('dd',v));}detail.append(info);
 const wa=node('a','Conversar pelo WhatsApp ↗','button primary');wa.href='https://wa.me/'+item.phone+'?text='+encodeURIComponent(`Olá, ${item.name}! Aqui é a Pryme Digital. Recebemos seu pedido para ${item.business}. Podemos conversar sobre o projeto?`);wa.target='_blank';wa.rel='noopener noreferrer';detail.append(wa);
 detail.append(node('h3','Arquivos da marca','files-title'));if(!item.files.length)detail.append(node('p','Nenhuma imagem enviada.','muted'));
 item.files.forEach((f,index)=>{const b=node('button',f.name+' ↗','file-download');b.type='button';b.addEventListener('click',async()=>{b.disabled=true;try{const r=await api('file',{method:'POST',body:{id:item.id,index}});const a=node('a','Abrir imagem (link válido por 1 minuto)','text-link');a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';b.replaceWith(a);}catch(e){say(e.message);b.disabled=false;if(e.status===401)await locked();}});detail.append(b);});
 const f=document.createElement('form');f.className='admin-edit';const label=node('label','Etapa do pedido');const select=document.createElement('select');select.name='status';for(const [key,value]of Object.entries(statusNames)){const o=node('option',value);o.value=key;select.append(o);}select.value=item.status;label.append(select);
 const dateLabel=node('label','Próximo contato');dateLabel.className='next-contact';const nextContact=document.createElement('input');nextContact.type='date';nextContact.value=item.next_contact_at?item.next_contact_at.slice(0,10):'';dateLabel.append(nextContact);const notesLabel=node('label','Anotações internas');const notes=document.createElement('textarea');notes.name='notes';notes.rows=5;notes.maxLength=5000;notes.value=item.notes;notesLabel.append(notes);const save=node('button','Salvar alterações','button primary');save.type='submit';const feedback=node('p','','form-privacy');feedback.setAttribute('role','status');f.append(label,dateLabel,notesLabel,save,feedback);f.addEventListener('input',()=>{f.dataset.dirty='true';});
 f.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;feedback.textContent='Salvando…';try{const r=await api('lead-update',{method:'PATCH',body:{id:item.id,updated_at:item.updated_at,status:select.value,notes:notes.value,next_contact_at:nextContact.value}});Object.assign(item,r.item);f.dataset.dirty='false';feedback.textContent='Alterações salvas.';render();}catch(e){feedback.textContent=e.message;if(e.status===401)await locked();}finally{save.disabled=false;}});detail.append(f);detail.hidden=false;detail.focus();
}
login.addEventListener('submit',async e=>{e.preventDefault();if(!challenge?.token()){say('Conclua a verificação de segurança.');return;}const button=login.querySelector('button');button.disabled=true;say('Entrando…');try{await api('login',{method:'POST',body:{email:login.elements.email.value,password:login.elements.password.value,token:challenge.token()}});login.reset();login.hidden=true;panel.hidden=false;await load();}catch(e){say(e.message);}finally{button.disabled=false;challenge.reset();}});
document.querySelector('#logout').addEventListener('click',async()=>{try{await api('logout',{method:'POST',body:{}});await locked();say('Você saiu do painel.');}catch(e){say(e.message);}});
document.querySelector('#filter-form').addEventListener('submit',e=>{e.preventDefault();page=0;load();});document.querySelector('#filter').addEventListener('change',()=>{page=0;load();});document.querySelector('#previous').addEventListener('click',()=>{page--;load();});document.querySelector('#next').addEventListener('click',()=>{page++;load();});document.querySelector('#refresh').addEventListener('click',load);
window.addEventListener('beforeunload',e=>{if(detail.querySelector('form')?.dataset.dirty==='true'){e.preventDefault();e.returnValue='';}});
try{await api('session');login.hidden=true;panel.hidden=false;await load();}catch{await locked();}
