const models={
 personal:{brand:'SEU NOME / PERSONAL',tag:'TREINO COM PROPÓSITO',title:'SEU FOCO.\nSEU RITMO.',description:'Uma rotina de movimento pensada para você. Conheça meu trabalho e descubra como podemos começar.',cta:'Vamos conversar ↗',art:'FOCO',services:'Acompanhamento que cabe na sua vida.',items:[['Treino presencial','Um espaço para explicar sua abordagem no acompanhamento individual.'],['Consultoria online','Apresente como funciona seu atendimento a distância.'],['Objetivos claros','Mostre como você organiza as etapas do seu trabalho.']],about:'Muito além de uma série de exercícios.',bio:'Aqui entra sua trajetória, sua formação e o que torna seu atendimento único. Um texto verdadeiro, com a sua linguagem, para quem está conhecendo seu trabalho.',contact:'Vamos encontrar\nseu próximo passo?'},
 studio:{brand:'SEU STUDIO',tag:'MOVIMENTO & EQUILÍBRIO',title:'Movimento\nque faz bem.',description:'Um espaço para desacelerar, se fortalecer e encontrar seu ritmo. Conheça as práticas do nosso estúdio.',cta:'Conhecer o espaço ↗',art:'RESPIRA',services:'Um cuidado em cada prática.',items:[['Pilates','Apresente as características desta modalidade no seu espaço.'],['Mobilidade','Conte como são conduzidas as aulas e para quem são indicadas.'],['Funcional','Mostre sua proposta de movimento e acompanhamento.']],about:'Seu espaço de movimento e conexão.',bio:'Conte a história do seu estúdio e apresente as pessoas que fazem parte dele. Fotos reais do ambiente e da equipe dão personalidade a esta seção.',contact:'Reserve um momento\npara você.'},
 academia:{brand:'SUA ACADEMIA',tag:'ENERGIA PARA IR ALÉM',title:'O PRÓXIMO\nNÍVEL É SEU.',description:'Estrutura, movimento e uma rotina que acompanha você. Conheça as modalidades e encontre seu jeito de treinar.',cta:'Conhecer os planos ↗',art:'MOVE',services:'Seu treino começa aqui.',items:[['Musculação','Apresente os equipamentos e a estrutura disponíveis.'],['Aulas coletivas','Mostre as modalidades e os horários das turmas.'],['Acompanhamento','Explique como funciona a orientação dentro da academia.']],about:'Um lugar para fazer acontecer.',bio:'Aqui você apresenta a estrutura da academia, a localização e os diferenciais reais do seu atendimento. Sem números inventados: somente o que seu espaço oferece.',contact:'Vamos começar\na sua nova rotina?'}
};
const key=new URLSearchParams(location.search).get('modelo');const id=Object.hasOwn(models,key)?key:'personal';const m=models[id];document.body.className=id;document.title=m.brand+' — Demonstração Pryme';
for(const [selector,value]of Object.entries({'#demo-brand':m.brand,'#demo-tag':m.tag,'#demo-title':m.title,'#demo-description':m.description,'#demo-cta':m.cta,'#art-word':m.art,'#services-title':m.services,'#about-title':m.about,'#about-text':m.bio,'#contact-title':m.contact,'#footer-brand':m.brand}))document.querySelector(selector).textContent=value;
for(const idSelector of ['#choose','#end-choose'])document.querySelector(idSelector).href='pedido.html?modelo='+id;
const container=document.querySelector('#service-cards');for(const [index,[title,text]]of m.items.entries()){const card=document.createElement('article');const n=document.createElement('span');n.textContent='0'+(index+1);const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=text;card.append(n,h,p);container.append(card);}
if(id!=='personal'){const extra=document.querySelector('#extra');extra.hidden=false;const h=document.createElement('h2');h.textContent=id==='studio'?'Conheça seu novo espaço.':'Planos e horários, sem complicar.';const p=document.createElement('p');p.textContent=id==='studio'?'Uma galeria com as fotos reais do seu estúdio e uma apresentação da equipe entram nesta área.':'Esta área apresenta os valores aprovados pela sua academia e a grade real de funcionamento.';const grid=document.createElement('div');grid.className='extras';for(let i=0;i<3;i++){const x=document.createElement('article');x.textContent=id==='studio'?['Seu ambiente','Sua equipe','Sua experiência'][i]:['Plano mensal · valor a definir','Plano semestral · valor a definir','Horários · grade a definir'][i];grid.append(x);}extra.append(h,p,grid);}
